language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed           #feed
  - docker tag udagram-api-feed tdchien96/udagram-api-feed:v1 #feed
  - docker build -t udagram-api-user ./udagram-api-user           #user
  - docker tag udagram-api-user tdchien96/udagram-api-user:v1 #user
  - docker build -t udagram-frontend ./udagram-frontend           #frontend
  - docker tag udagram-frontend tdchien96/udagram-frontend:v1 #frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy   #reverseproxy
  - docker tag udagram-reverseproxy tdchien96/reverseproxy:v1 #reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tdchien96/udagram-api-feed
  - docker push tdchien96/udagram-api-user
  - docker push tdchien96/udagram-frontend
  - docker push tdchien96/reverseproxy

