language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed tdchien96/udagram-api-feed:v1 #feed
  - docker tag udagram-api-user tdchien96/udagram-api-user:v1 #user
  - docker tag udagram-frontend:local tdchien96/udagram-frontend:v1 #frontend
  - docker tag udagram-reverseproxy tdchien96/reverseproxy:v1 #reverseproxy

after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tdchien96/udagram-api-feed:udagram-api-feed
  - docker push tdchien96/udagram-api-user:udagram-api-user
  - docker push tdchien96/udagram-frontend:udagram-frontend
  - docker push tdchien96/reverseproxy:udagram-reverseproxy

