apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user-app
  name: backend-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-user
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-user-app
