apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-app
  name: frontend-app-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/frontend-app-svc
spec:
  ports:
  - port: 8100
    targetPort: 80
  selector:
    app: frontend-app
  type: LoadBalancer
status:
  loadBalancer: {}
