apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverseproxy-app
  name: reverseproxy-app-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/reverseproxy-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
